version: '3'
services:
  db:
    image: mysql:8.0.22
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: fanfiction_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
