version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:15-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}

      - run: gradle clean

      - run: gradle test

      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build/test-results/test

      - run: gradle build
